version: "3"
services:
  cyber-gateway:
    image: xxxxx/cyber-gateway:1.0.0
    container_name: cyber-gateway
    restart: always
    ports:
      - "8888:8888"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - ACTIVE_PROFILE=test
    volumes:
      - /opt/cyber/logs:/opt/cyber/logs/
    logging:
      driver: "json-file" # 默认的文件日志驱动
      options:
        max-size: "50m"
        max-file: "1"

  cyber-auth-center:
    image: xxxxx/cyber-auth-center:1.0.0
    container_name: cyber-auth-center
    restart: always
    ports:
      - "8033:8033"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - ACTIVE_PROFILE=test
    volumes:
      - /opt/cyber/logs:/opt/cyber/logs/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  cyber-api:
    image: xxxxx/cyber-api:1.0.0
    container_name: cyber-api
    restart: always
    ports:
      - "8023:8023"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - ACTIVE_PROFILE=test
    volumes:
      - /opt/cyber/logs:/opt/cyber/logs/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"