version: "3"
services:
  vita-gateway:
    image: xxxxx/vita-gateway:1.0.0
    container_name: vita-gateway
    restart: always
    ports:
      - "8888:8888"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - ACTIVE_PROFILE=test
    volumes:
      - /opt/vita/logs:/opt/vita/logs/
    logging:
      driver: "json-file" # 默认的文件日志驱动
      options:
        max-size: "50m"
        max-file: "1"

  vita-auth-center:
    image: xxxxx/vita-auth-center:1.0.0
    container_name: vita-auth-center
    restart: always
    ports:
      - "8033:8033"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - ACTIVE_PROFILE=test
    volumes:
      - /opt/vita/logs:/opt/vita/logs/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  vita-api:
    image: xxxxx/vita-api:1.0.0
    container_name: vita-api
    restart: always
    ports:
      - "8023:8023"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - ACTIVE_PROFILE=test
    volumes:
      - /opt/vita/logs:/opt/vita/logs/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"