server:
  port: 8023
  servlet:
    context-path: /

spring:
  application:
    name: cyber-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: cyber-dev
        group: dev

# 接口文档配置
knife4j:
  enable: true
  basic:
    enable: true
    username: cyber
    password: cyber

# 日志级别
logging:
  level:
    root: debug
